# Generated by Django 5.0 on 2023-12-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(blank=True, default='https://cdn-icons-png.flaticon.com/512/1377/1377194.png', max_length=5000, null=True),
        ),
    ]
